#!/bin/bash

# This is a small script to add
# to a spell check on the fly.

# Designed to be activated in vim
# with :!spell <wrong> <correct>

if [[ "${1}" =~ [A-Z0-9] ]]; then
  echo "  :iabbrev ${1} ${2}" >> "${HOME}/.vim/vimrc"
else
  echo "  :iabbrev ${1} ${2}" >> "${HOME}/.vim/vimrc"
  One="$(tr '[:lower:]' '[:upper:]' <<< ${1:0:1})${1:1}"
  Two="$(tr '[:lower:]' '[:upper:]' <<< ${2:0:1})${2:1}"
  echo "  :iabbrev ${One} ${Two}" >> "${HOME}/.vim/vimrc"
fi
