#!/bin/bash 

# Install Vim by Script

# VIM Plug, for 'Goyo' mainly
  curl -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs \ 
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  
# TODO: copy files, link, etc.

  if [ ! -d "${HOME}/.config" ] ; then mkdir ${HOME}/.config ; fi
  cp -r ../vim ${HOME}/.config/.
  echo "Complete"
