#!/bin/bash 

# Install Vim by Script

# Copy Files To Correct Place
  echo ""
  if [ ! -d "${HOME}/.config" ] ; then mkdir ${HOME}/.config ; fi
  cp -r ../vim ${HOME}/.config/.
  sudo rm -r ${HOME}/.vim/
  ln -sf ${HOME}/.config/vim ${HOME}/.vim  

# VIM Plug, for 'Goyo' mainly
  echo ""
  curl -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  echo ""
 
  ls -la ${HOME}/.config/vim
